version: "3.4"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      DATABASE_CONNECTION: "mongodb://mongodb-sharded:27017/cpe-kmutt-web"
      DATABASE_USERAME: root
      DATABASE_PASSWORD: CPE-KMUTT-DB
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: very-secret-key.jwt
      JWT_EXPIRES: 3600s
      OPS_KEY: "CPE-KMUTT.opskey"
      NODE_ENV: "development"
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - "./backend:/backend/src"
    command: yarn start:dev
    links:
      - mongos
      - shard-0
      - mongodb-cfg
    restart: always

  mongos:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-sharded
      MONGODB_SHARDING_MODE: mongos
      MONGODB_CFG_PRIMARY_HOST: mongodb-cfg
      MONGODB_CFG_REPLICA_SET_NAME: cfgreplicaset
      MONGODB_REPLICA_SET_KEY: CPE-KMUTT-DB-CLUSTER
      MONGODB_ROOT_PASSWORD: CPE-KMUTT-DB
      TZ: Asia/Bangkok
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/mongos:/bitnami"
  shard-0:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-shard0
      MONGODB_SHARDING_MODE: shardsvr
      MONGODB_MONGOS_HOST: mongodb-sharded
      MONGODB_ROOT_PASSWORD: CPE-KMUTT-DB
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: CPE-KMUTT-DB-CLUSTER
      MONGODB_REPLICA_SET_NAME: shard0
      TZ: Asia/Bangkok
    volumes:
      - "./mongo/shard0_data:/bitnami"
  mongodb-cfg:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-cfg
      MONGODB_SHARDING_MODE: configsvr
      MONGODB_ROOT_PASSWORD: CPE-KMUTT-DB
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: CPE-KMUTT-DB-CLUSTER
      MONGODB_REPLICA_SET_NAME: cfgreplicaset
      TZ: Asia/Bangkok
    volumes:
      - "./mongo/mongodb-cfg:/bitnami"

