version: "3.4"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      WAIT_HOSTS: mongo:27017
      TZ: Asia/Bangkok
      ORIGIN: http(|s):\/\/localhost:5000
      DATABASE_CONNECTION: "mongodb://mongodb-sharded:27017/cpe-kmutt-web"
      DATABASE_USERAME: root
      DATABASE_PASSWORD: cpeKMUTT@WebSite
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: very-secret-key.jwt
      JWT_EXPIRES: 3600s
      OPS_KEY: "CPE-KMUTT.opskey"
      NODE_ENV: "development"
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - "./backend:/backend"
    links:
      - mongodb-shard0
    command: yarn start:dev
    restart: always
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb-sharded
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: cpeKMUTT@WebSite
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mongodb-sharded
  mongos:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongos
      MONGODB_SHARDING_MODE: mongos
      MONGODB_CFG_PRIMARY_HOST: cfg
      MONGODB_CFG_REPLICA_SET_NAME: cfgreplicaset
      MONGODB_REPLICA_SET_KEY: cpekmuttweb
      MONGODB_ROOT_PASSWORD: cpeKMUTT@WebSite
      TZ: Asia/Bangkok
    ports:
      - "27017:27017"
  shard0:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: shard0
      MONGODB_SHARDING_MODE: shardsvr
      MONGODB_MONGOS_HOST: mongos
      MONGODB_ROOT_PASSWORD: cpeKMUTT@WebSite
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: cpekmuttweb
      MONGODB_REPLICA_SET_NAME: shard0
      TZ: Asia/Bangkok
    volumes:
      - "./db/shard-0:/bitnami"
  cfg:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: cfg
      MONGODB_SHARDING_MODE: configsvr
      MONGODB_ROOT_PASSWORD: cpeKMUTT@WebSite
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: cpekmuttweb
      MONGODB_REPLICA_SET_NAME: cfgreplicaset
      TZ: Asia/Bangkok
    volumes:
      - "./db/cfg:/bitnami"
