version: "3"
services:
  proxy:
    container_name: proxy
    restart: on-failure
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - strapi
      - mongodb
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  frontend:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      TZ: Asia/Bangkok
      STRAPI_ENDPOINT: http://beta.cpe.kmutt.ac.th/strapi/
      APP_GRAPHQL_ENDPOINT: http://beta.cpe.kmutt.ac.th/strapi/
    depends_on:
      - strapi
    deploy:
      mode: replicated
      replicas: 3
  backend:
    container_name: cpe-kmutt-backend-prod
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      WAIT_HOSTS: mongo:27017
      TZ: Asia/Bangkok
      ORIGIN: http(|s):\/\/localhost:5000
      DATABASE_CONNECTION: "mongodb://mongodb:27017/cpe-kmutt-web"
      DATABASE_USERAME: root
      DATABASE_PASSWORD: cpeKMUTT@WebSite
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: very-secret-key.jwt
      JWT_EXPIRES: 3600s
      OPS_KEY: "CPE-KMUTT.opskey"
      NODE_ENV: "development"
      PORT: 3000
    volumes:
      - "./backend:/backend"
    links:
      - mongodb
    command: yarn start:dev
  strapi:
    container_name: cpe-kmutt-strapi-prod
    restart: on-failure
    build:
      context: ./strapi
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: cpeKMUTT@WebSite
    volumes:
      - ./uploads/:/app/public/uploads
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: "bitnami/mongodb:latest"
    restart: on-failure
    environment:
      MONGODB_ROOT_PASSWORD: cpeKMUTT@WebSite
      TZ: Asia/Bangkok
    volumes:
      - "./db:/bitnami"
