name: Automate Build and Testing Front-end

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14-latest
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache node_modules
      - uses: actions/cache@v2
          id: yarn-cache
          with:
            path: |
              **/node_modules
              **/.eslintcache
              ${{ steps.yarn-cache-dir-path.outputs.dir }}

            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14-latest
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
      - uses: actions/cache@v2
          id: yarn-cache
          with:
            path: |
              **/node_modules
              **/.eslintcache
              ${{ steps.yarn-cache-dir-path.outputs.dir }}

            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn storybook:build
