name: Storybook Build Front-end

on:
  pull_request:
    branches:
      - main
  on:
    push:
      paths:
        - '**/*.stories.tsx'

defaults:
  run:
    working-directory: frontend

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14-latest
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-
      - run: yarn
      - run: yarn storybook:build
